source $HOME/.shellrc/lang.bash
source $HOME/.shellrc/default-path.bash
source $HOME/.shellrc/homebrew.bash
source $HOME/.shellrc/autojump.bash
source $HOME/.shellrc/editor.bash
source $HOME/.shellrc/git-prompt.zsh
source $HOME/.shellrc/go.bash
source $HOME/.shellrc/groovy.bash
source $HOME/.shellrc/jenv.bash
source $HOME/.shellrc/mysql.bash
source $HOME/.shellrc/node.bash
source $HOME/.shellrc/pear.bash
source $HOME/.shellrc/python.bash
source $HOME/.shellrc/ruby.bash
source $HOME/.shellrc/svn-hg.bash
source $HOME/.shellrc/misc.zsh
source $HOME/.shellrc/custom-scripts.bash
